### ISSUE TITLE
'swarm up' creates panic

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#523]
Trying to create a service on leaseweb-alpha using this service definition

```
{
  "name": "busywait",
  "components": {
    "box": {
      "image": "busybox:latest",
      "args": [
        "sh",
        "-c",
        "while true; do echo \"Hello world\"; sleep 10; done"
      ],
      "scale": {
        "placement": "one-per-machine",
        "min": 10
      }
    }
  }
}
```

... and this command:

```
SWARM_CLUSTER_ID=leaseweb-alpha-private.giantswarm.io swarm --config-dir=/Users/marian/.leasewebswarm up
```

This is the output I got:

```
Creating 'busywait' in the 'marian/dev' environment…
Service created successfully!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x231ad]

goroutine 1 [running]:
main.processUp(0x0, 0x0)
	/usr/code/up.go:96 +0x75d
main.upCmdRun(0x783a20, 0xc820157530, 0x0, 0x1)
	/usr/code/up.go:64 +0x2e
github.com/spf13/cobra.(*Command).execute(0x783a20, 0xc8201574e0, 0x1, 0x1, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:530 +0x869
github.com/spf13/cobra.(*Command).Execute(0x782a60, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:613 +0x46a
main.main()
	/usr/code/main.go:103 +0xc9c

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 12 [IO wait]:
net.runtime_pollWait(0x9f1f40, 0x72, 0xc8200121a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201d00d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201d00d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201d0070, 0xc8201e4400, 0x400, 0x400, 0x0, 0x9ec050, 0xc8200121a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201d2008, 0xc8201e4400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201ce2d0, 0xa2c130, 0xc8201d2008, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201e2000, 0x5f2c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201e2000, 0xc82036a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x9f6c00, 0xc8201e2000, 0xc82013fa78, 0xc82036a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820435fc0, 0xc82036a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820416a80)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820416a80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82013fa20)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc82013fa20)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
```

In another attempt, I could not reproduce this.

The CLI should always die gracefully, never panic.

**Comment by marians** [comment]
I could reproduce this now, including "debug" switch on.

```
[marian:~/git/support/hotswap-update-machinelimit] 4m20s $ lwswarm --debug up
DEBUG: request ID 'rl3gwm1v65mljk23'
DEBUG: GET https://api.giantswarm.io/v1/org/marian/env/dev/service/busywait/status
DEBUG: << 400 Bad Request
Creating 'busywait' in the 'marian/dev' environment…
DEBUG: POST https://api.giantswarm.io/v1/org/marian/env/dev/service/ (application/json)
DEBUG: << 200 OK
Service created successfully!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x231ad]

goroutine 1 [running]:
main.processUp(0x0, 0x0)
	/usr/code/up.go:96 +0x75d
main.upCmdRun(0x783a20, 0xc82017f020, 0x0, 0x2)
	/usr/code/up.go:64 +0x2e
github.com/spf13/cobra.(*Command).execute(0x783a20, 0xc82017eee0, 0x2, 0x2, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:530 +0x869
github.com/spf13/cobra.(*Command).Execute(0x782a60, 0x0, 0x0)
	/usr/code/.gobuild/src/github.com/spf13/cobra/command.go:613 +0x46a
main.main()
	/usr/code/main.go:103 +0xc9c

goroutine 17 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 38 [IO wait]:
net.runtime_pollWait(0xa2de98, 0x72, 0xc8200101a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820181aa0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820181aa0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820181a40, 0xc8200a3c00, 0x400, 0x400, 0x0, 0x9ec050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200b24e0, 0xc8200a3c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201bce70, 0xa2e208, 0xc8200b24e0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82020a000, 0x5f2c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82020a000, 0xc820191000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xa76040, 0xc82020a000, 0xc820165bd8, 0xc820191000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82047f9e0, 0xc820191000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820208300)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820208300, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820165b80)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 39 [select]:
net/http.(*persistConn).writeLoop(0xc820165b80)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

[marian:~/git/support/hotswap-update-machinelimit] 39s 2 $ lwswarm --debug status -v
DEBUG: request ID '44s3q86yvj8kwxs5'
DEBUG: GET https://api.giantswarm.io/v1/org/marian/env/dev/service/busywait/status
DEBUG: << 200 OK
Service busywait is down

component  image           imageid  instanceid    podid         created              status
box        busybox:latest  n/a      24i45s353n9o  24i45s353n9o  2015-12-08 16:46:23  down
box        busybox:latest  n/a      5nbe0jgptvx8  5nbe0jgptvx8  2015-12-08 16:46:16  down
box        busybox:latest  n/a      66ks919cfbsc  66ks919cfbsc  2015-12-08 16:46:34  down
box        busybox:latest  n/a      923ozb76l1wt  923ozb76l1wt  2015-12-08 16:46:20  down
box        busybox:latest  n/a      lqumebygbgun  lqumebygbgun  2015-12-08 16:46:38  down
box        busybox:latest  n/a      ygwpm2zjpbf7  ygwpm2zjpbf7  2015-12-08 16:46:42  down
box        busybox:latest  n/a      z0yqvudvfm5i  z0yqvudvfm5i  2015-12-08 16:46:46  down
box        busybox:latest  n/a      z3ze4653xkrj  z3ze4653xkrj  2015-12-08 16:46:28  down

[marian:~/git/support/hotswap-update-machinelimit] 8s $ lwswarm --debug cat
DEBUG: request ID '4l3ipj3bag453wxs'
DEBUG: GET https://api.giantswarm.io/v1/org/marian/env/dev/service/busywait/definition
DEBUG: << 200 OK
{
  "name": "busywait",
  "components": {
    "box": {
      "image": "busybox:latest",
      "args": [
        "sh",
        "-c",
        "while true; do echo \"Hello world\"; sleep 10; done"
      ],
      "scale": {
        "min": 10,
        "placement": "one-per-machine"
      }
    }
  }
}
```

[Log entries for request rl3gwm1v65mljk23](https://leaseweb-kibana.giantswarm.io/#/discover?_a=(columns:!(unit,logtext),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'logtext:%22rl3gwm1v65mljk23%22')),sort:!('@timestamp',asc))&_g=(time:(from:'2015-12-08T16:46:08.470Z',mode:absolute,to:'2015-12-08T16:46:53.924Z')))

**Comment by marians** [comment]
@ewoutp @zeisss : Any idea how https://github.com/giantswarm/cli/blob/master/up.go#L96 can create a panic `invalid memory address or nil pointer dereference`? What value would `status` have to have so that this could happen?

**Comment by ewoutp** [comment]
I cannot think of a proper reason why it can panic here.
It this reproducable with a clean master build?

**Comment by zeisss** [comment]
Are you sure you had the latest commits? Tim fixed a panic in that exact file 2 weeks ago with https://github.com/giantswarm/cli/commit/a7d6c4c4f61668510232efa68d40a340585d1303

**Comment by marians** [comment]
Unfortunately I am not sure what exact version I used. And I wasn't able to reproduce the panic.

@zeisss The change you are pointing to seems to fix exactly that, as you say. Accessing a `.Name` property of a `nil` value in line 96 of `up.go`.

Closing this, as it seems to be fixed. Thanks!
